StackStorm/orquesta

- orchestra/composers/mistral.py
- orchestra/composition.py
- orchestra/tests/unit/base.py
- orchestra/tests/unit/composition/mistral/test_workflow_graph.py
Rename the term "sequence" between tasks to "transition" in workflow graph.
> Rename the term sequence to transition in workflow graph

- docs/dsl/orchestra/examples/branching.yaml
- docs/dsl/orchestra/examples/error_handling.yaml
- docs/dsl/orchestra/examples/join.yaml
- docs/dsl/orchestra/examples/retry.yaml
- docs/dsl/orchestra/examples/rollback_and_retry.yaml
- docs/dsl/orchestra/examples/sequential.yaml
- docs/dsl/orchestra/examples/with_items.yaml
- docs/dsl/orchestra/examples/with_multi_items.yaml
- docs/dsl/orchestra/spec.md
This is the first draft of the orchestra workflow DSL. The spec is derived from Mistral. There are examples of workflow use cases such as sequential, parallel branches, barrier, with-items, retries, and etc. Please refer to the discussion at StackStorm/discussions#270 for more information on intent and motivation.
> Draft of the orchestra workflow DSL

- orquesta/expressions/base.py
- orquesta/expressions/jinja.py
- orquesta/expressions/yql.py
- orquesta/specs/mistral/v2/policies.py
- orquesta/specs/mistral/v2/tasks.py
- orquesta/specs/native/v1/models.py
- orquesta/specs/types.py
- orquesta/tests/unit/expressions/test_facade.py
Remove YAQL schema from base types in spec. Add methods in facade for working with expressions.
> Minor refactoring of schemas and expressions

- Makefile
- bin/orquesta-generate-schemas
- docs/source/schemas/orquesta.json
Add script and command in Makefile to generate schema file for the workflow definition(s).
> Add make command to generate schema for the workflow definition

- bin/orquesta-generate-schemas
- docs/source/schemas/mistral.json
Update schema generation script to include mistral models to temporary support backward compatibility in st2flow.
> Update schema generation script to include mistral models

- setup.py
Update the python version to 3.6 in the project classification at setup file.
> Update python version in project meta

- orquesta/composers/native.py
- requirements.txt
Add sleep in while loop of composer to yield cpu to other threads/processes.
> Add sleep in while loop of composer to yield cpu

- CHANGELOG.rst
- orquesta/__init__.py
Update version to 0.4 and add entries in CHANGELOG for the release.
> Update version to 0.4

- docs/source/yaql.rst
- orquesta/tests/unit/conducting/test_workflow_conductor_context.py
- orquesta/tests/unit/expressions/test_yaql_ctx_query.py
Add more unit tests to cover the use of YAQL on context vars and fix sample YAQL query in docs.
> Update yaql tests docs

- .gitignore
Add an entry in .gitignore for the .vscode directory created by Visual Studio Code.
> Add entry in .gitignore for vscode directory

- orquesta/expressions/functions/workflow.py
- orquesta/tests/unit/conducting/test_workflow_conductor_with_items.py
Fix issue where item returns None when value evaluate to False such as empty string, dict, or list. Fixes https://github.com/StackStorm/st2/issues/4618.
> Fix return value of item that evaluate to false

- docs/source/development/get_started.rst
- docs/source/development/index.rst
- docs/source/development/st2.rst
Add syntax highlighting to Bash code blocks, and rearrange the TOC in the index for better flow.
> A few changes on top of dev-docs PR

- CHANGELOG.rst
- orquesta/__init__.py
Update version to 0.5 and add entries in CHANGELOG for the release.
> Update version to 0.5

- docs/source/languages/orquesta.rst
> small language change in docs

- docs/source/languages/orquesta.rst
Small changes to language and fixed a typo
> Minor docs typo & language change

- CHANGELOG.rst
- orquesta/__init__.py
Change the version number to the semver format and from 0.6 -> 1.0.0 to indicate GA.
> Change the version number to the semver format

- orquesta/exceptions.py
Fix the init method of exception classes to use the super method for init.
> Fix the init method of exception classes

- orquesta/conducting.py
- orquesta/tests/unit/conducting/test_workflow_conductor_rerun.py
Fix rerun to identify duplicate task requests or task requests that will lead to duplicate reruns.
> Fix rerun to identify duplicate task requests

- CHANGELOG.rst
- orquesta/__init__.py
Preparing a release of orquesta for st2. Update orquesta version from 1.0.0 to 1.1.0.
> Update version to 1.1.0

- CHANGELOG.rst
- orquesta/__init__.py
A patch release v1.1.1 with bug fix for pre-release testing of StackStorm v3.2.
> Patch release v1.1.1 with bug fix for st2 v3.2

- Makefile
- bin/orquesta-generate-schemas
- docs/source/schemas/mistral.json
- docs/source/schemas/orquesta.json
- tox.ini
Regenerate schemas for the workflow definition models and update CI to return error if there are uncommitted schema changes.
> Regenerate schemas for the workflow definition models

- orquesta/specs/native/v1/models.py
- orquesta/tests/unit/specs/native/test_workflow_spec_validate.py
Add step in the workflow inspection to return error if the workflow has tasks defined but no start tasks can be identified.
> Return error if workflow has tasks but no start tasks

- CHANGELOG.rst
- orquesta/__init__.py
Preparing a release of orquesta for st2. Update orquesta version from 1.1.1 to 1.2.0.
> Update version to 1.2.0

- CHANGELOG.rst
- orquesta/__init__.py
- setup.py
Preparing a release of orquesta for st2. Update orquesta version from 1.2.1 to 1.3.0.
> Update version to 1.3.0

- .github/workflows/tox.yml
Currently, the github action is not triggered for PR from fork. Add an event in the workflow to trigger on pull request to master branch.
> Add event to github action to trigger on pull request

- Makefile
> Update to same pip as ST2

- .flake8
- CHANGELOG.rst
- orquesta/__init__.py
Preparing a release of orquesta for st2. Update orquesta version from 1.3.0 to 1.4.0.
> Update version to 1.4.0

- CHANGELOG.rst
- orquesta/__init__.py
Preparing a release of orquesta for st2. Update orquesta version from 1.4.0 to 1.5.0.
> Update version to 1.5.0
