- orchestra/expressions/jinja.py
- orchestra/tests/unit/expressions/test_jinja_evaluate.py
Add support for raw blocks in jinja expression. Expressions and variables wrapped in raw blocks will not be evaluated.
> Add support for raw blocks in jinja expression

- orchestra/composers/base.py
- orchestra/specs/base.py
- orchestra/specs/loader.py
- orchestra/specs/mistral/v2/base.py
- orchestra/specs/mock/workflows.py
- orchestra/tests/unit/specs/mistral/test_base_spec.py
- orchestra/tests/unit/specs/test_base_spec.py
- orchestra/tests/unit/specs/test_spec_loader.py
Add a helper function to retrieve the catalog name (i.e. mistral) from a spec class or instance.
> Add function to get catalog name from a spec class

- .travis.yml
- orchestra/expressions/jinja.py
- orchestra/expressions/yql.py
- tox.ini
StackStorm supports python 3.6. Some tests here passes on python 3.5 but not on 3.6. Move to the same python version to pass tests in StackStorm.
> Migrate from py35 to py36

- orchestra/conducting.py
Currently, only ExpressionEvaluationException are caught. There are cases when rendering task spec or evaluating task transition that the expression functions, task rendering step, or task transition evaluation step is returning other types of exception. The try blocks are modified to catch a more general exception type.
> Handle expression functions returning other exception types

- orchestra/utils/specs.py
Same change as in https://github.com/StackStorm/st2/pull/4223.
There is no need to use `yaml.load` when loading workflow definition files since we only support simple types there (integers, strings, lists, etc.).
`yaml.safe_load` is preferred in such scenarios and `yaml.load` could present security issues since it also supports loading arbitrary Python objects.
> Use yaml.safe_load instead of yaml.load

- orquesta/conducting.py
- orquesta/states/machines.py
- orquesta/tests/unit/conducting/test_task_flow.py
- orquesta/tests/unit/states/native/test_workflow_branching.py
- orquesta/tests/unit/states/native/test_workflow_sequential.py
Task and action execution go into pending state when waiting for human input. This effectively puts the task execution into a paused state. The pending state is added to the conductor function that queries for task in paused state. A bug is also fixed when updating task flow. If the task is not ready and an update is requested, throw an exception. This bug causes inaccurate unit tests that cover pending tasks.
> Fix state management for task in pending state

- orquesta/tests/unit/conducting/test_workflow_conductor.py
Add unit tests to cover repeated calls to get next tasks from conductor. Repeated calls should not include tasks that already started running.
> Add unit tests to cover repeated calls to get next tasks

- .flake8
- .pylintrc
- orquesta/expressions/jinja.py
- orquesta/specs/mistral/__init__.py
- orquesta/specs/mistral/v2/__init__.py
- orquesta/specs/mock/__init__.py
- orquesta/specs/native/__init__.py
- orquesta/specs/native/v1/__init__.py
- orquesta/tests/hacking/__init__.py
- orquesta/tests/hacking/imports.py
- tox.ini
Add the following flake8 rules to restrict import styles.
- not allow import of more than one module per line
- not allow wildcard (*) imports
- not allow relative imports
- not allow non-module imports
> Add flake8 rules to restrict import styles

- orquesta/specs/base.py
- orquesta/tests/unit/specs/test_base_spec.py
Applications for the workflow engine can provide context for workflow execution at runtime. These context are application specific such as execution ID, API URL, etc that may not be friendy to require declaration in every workflow definition. The spec inspection method is refactored to allow optional application context to properly validate references to variables in the context.
> Inspect context provided by app but not declared explicitly

- orquesta/expressions/base.py
- orquesta/expressions/functions/common.py
- orquesta/expressions/jinja.py
- orquesta/tests/unit/expressions/functions/test_common.py
- orquesta/tests/unit/expressions/test_facade.py
Check for context argument in the expression function before registrating it with the Jinja evaluator. This allows general and common functions to not have to unnecessary include a context argument.
> Check for context argument in function before registration

- CHANGELOG.rst
- orquesta/conducting.py
- orquesta/tests/unit/conducting/test_task_flow.py
Reviewed and clean up some of the public methods in the conductor class. These methods are indicated private (not enforced) to help with best practices.
> Clean up public methods in conductor

- CHANGELOG.rst
- orquesta/conducting.py
- orquesta/tests/unit/conducting/test_task_flow.py
Add an error entry in the conductor errors log when a failed execution event is received by update_task_flow.
> Log error when a failed execution event is received

- Makefile
Add make command to create the package for upload to pypi. The command to upload to pypi must be run separately on the dist directory. Remove make commands to create rpm and deb packages since those are not in use.
> Add command to make package for upload to pypi

- orquesta/expressions/jinja.py
- orquesta/expressions/yql.py
- orquesta/tests/unit/conducting/native/test_task_rendering_for_with_items.py
- orquesta/tests/unit/conducting/test_workflow_conductor_error_handling.py
- orquesta/tests/unit/expressions/test_jinja_eval_by_function_arg.py
- orquesta/tests/unit/expressions/test_yaql_eval_by_function_arg.py
- orquesta/tests/unit/utils/test_strings.py
- orquesta/utils/strings.py
Make strings in context unicode by default. This will avoid problems with manipulating strings of mix ascii and unicode type in expressions.
> Convert strings in context to unicode

- requirements.txt
Add chardet explicitly in requirements.txt as it is causing build failure downstream because of missing dependency.
> Add chardet to requirements.txt

- orquesta/conducting.py
- orquesta/tests/unit/conducting/test_workflow_conductor.py
- orquesta/tests/unit/conducting/test_workflow_conductor_error_handling.py
- orquesta/tests/unit/specs/native/test_workflow_spec_validate_vars.py
Previously, workflow output is processed only when workflow succeeds. This patch enables workflow output to be processed when workflow completes, regardless of success or failure. If there is a evaluation error, the line item in the output will be skipped and evaluation error recorded. When there is an output evaluation error, the workflow will be marked as failed.
> Process workflow output in other completed states

- docs/source/overview.rst
- orquesta/conducting.py
- orquesta/tests/unit/conducting/test_workflow_conductor.py
- orquesta/tests/unit/conducting/test_workflow_conductor_cancel.py
If a workflow is already expired, abandoned, or canceled and there are errors rendering workflow output, keep the workflow state as is and don't change it to failed.
> Fix state change when workflow output fails rendering

- orquesta/conducting.py
- orquesta/specs/mistral/v2/workflows.py
- orquesta/specs/native/v1/models.py
- orquesta/tests/unit/conducting/test_workflow_conductor_context.py
Fix the construction sequence of the workflow initial context. Assign the app context as the initial context before the workflow input and vars are rendered. This allows expressions in vars and input to reference variables set in the app context.
> Fix vars and input that references app context

- docs/source/expressions.rst
- docs/source/languages/orquesta.rst
- docs/source/schemas/orquesta.json
- orquesta/conducting.py
- orquesta/specs/native/v1/models.py
- orquesta/tests/unit/base.py
- orquesta/tests/unit/conducting/test_task_rendering.py
- orquesta/tests/unit/specs/native/test_task_spec.py
Add delay property to task model of native spec. The delay property specifies how many seconds to wait before the task and subsequent action execution.
> Add delay property to task model of native spec

- orquesta/conducting.py
- orquesta/tests/fixtures/workflows/native/splits-mixed.yaml
- orquesta/tests/unit/base.py
- orquesta/tests/unit/conducting/native/test_workflow_split.py
- orquesta/tests/unit/conducting/test_workflow_conductor_with_items.py
Fix a condition for with items task where the items list is empty. Before the patch, when the conductor get next tasks, the with items task will not be included in next tasks because the list is empty. The conductor is refactored to return the with items task in next tasks but without any action specs. The service using conductor will have to handle this accordingly to complete the with items task appropriately. The reasoning here is that the service such as StackStorm also maintains DB records for the task execution. Therefore, the conductor cannot auto forward to the next task but let the service manually handle the task execution even though the items list is empty and then manually forward the workflow progress.
>  Fix conductor get next tasks for with items task with empty list

- docs/source/languages/orquesta.rst
An image speaks a thousand words, so hopefully these ASCII art diagrams will be worth at least five hundred words.
Some users still had questions about the `join` task attribute. These ASCII art diagrams should hopefully illustrate its use in a workflow to modify the execution graph.
> Add ASCII art diagrams to illustrate the join task attribute

- orquesta/graphing.py
- orquesta/tests/unit/base.py
- orquesta/tests/unit/composition/native/base.py
- orquesta/tests/unit/graphing/native/test_routes_basic.py
- orquesta/tests/unit/graphing/native/test_routes_cycle.py
- orquesta/tests/unit/graphing/native/test_routes_join.py
- orquesta/tests/unit/graphing/native/test_routes_split.py
- orquesta/tests/unit/graphing/native/test_routes_task_transition.py
- orquesta/tests/unit/graphing/test_workflow_graph.py
Add a function in workflow graph to identify all possible routes as a function of the leaves or leaf clusters (closed cycles) in the graph.
> Add get_routes function to workflow graph

- orquesta/specs/native/v1/models.py
- orquesta/tests/unit/conducting/native/test_task_rendering_for_with_items.py
It's simple fix of the following issue
This workflow returns `TypeError: The value of "s) %>" is not type of list.` because "domains" contains 'in' 
```
version: 1.0
input:
- domains
tasks:
sk_update_domains:
with:
items: <% ctx(domains) %>
concurency: 2
action: i371.sk_update_domain domain=<% item() %>
```
> Fix for variables containing 'in'

- orquesta/tests/unit/utils/test_parameters.py
- orquesta/utils/parameters.py
https://github.com/StackStorm/orquesta/issues/119
Failure to publish `True` to a variable using `shorthand format`
The root cause:
For this issue is that when `parse_inline_params` is called, it checks regular expression against `'true'` (`REGEX_TRUE = 'true'`).  Since input value is `True`. it returns empty list `v=[]`. This is why publish value always equals to input value which is `false`.
If modify expression to `REGEX_TRUE = '(?i)true'` to ignore case, it passes regular expression check and return `v=['True'], when later `v = json.loads(v)` is called, it treats `True` as string and publish output will be `"True"` instead of `true`.
> Failure to publish `True` to a variable using `shorthand format

- docs/source/yaql.rst
Close issue https://github.com/StackStorm/orquesta/issues/124.
Passing true to decrypt of st2kv function does not work. 
This is documentation issue. The original documentation has wrong example.
Named parameters in function call must use the sign => for assignment. Equal sign = in YAQL is used for evaluation and will result in  the wrong value being passed for the parameter.
> Passing true to decrypt of st2kv function does not work

- orquesta/tests/unit/utils/test_parameters.py
- orquesta/utils/parameters.py
Fixes https://github.com/StackStorm/orquesta/issues/130
During `parse_inline_params` is called to parse parameters input, the leading and trailing single/double quotes is removed. Digit and True/False in quotes will be parsed as number and boolean type instead of String after `json.loads()`.
Solution:
For string in quotes (not includes dictionary  `'x=\'{\"a\": 1}\''`), 'json.loads' is not called.
> Value in quotes in shorthand publish should be evaluated as string type

- docs/source/context.rst
- docs/source/expressions.rst
Orquesta provides the ability to use expressions in action names and input values. This power can be extremely useful in certain workflow development scenarios, so much so that i believe it deserves its own tern which i'm calling the "dynamic execution pattern".
This pattern, as described in this PR, is taking the feature of expression in action names, describes how it works and wraps it up with a few examples.
> Added documentation about the dynamic execution pattern

- orquesta/conducting.py
- orquesta/specs/mistral/v2/tasks.py
- orquesta/specs/native/v1/models.py
- orquesta/tests/fixtures/workflows/native/join-context.yaml
- orquesta/tests/unit/base.py
- orquesta/tests/unit/conducting/native/test_workflow_join.py
- orquesta/tests/unit/conducting/native/test_workflow_split.py
- orquesta/tests/unit/conducting/native/test_workflow_task_transition.py
- orquesta/tests/unit/conducting/test_task_flow.py
- orquesta/tests/unit/conducting/test_workflow_conductor.py
- orquesta/tests/unit/conducting/test_workflow_conductor_branching.py
- orquesta/tests/unit/conducting/test_workflow_conductor_cycle.py
Refactor the internal data structure for storing task context. Previously, if there is change in context at task transition after publish, an entire copy of the context is stored. So when a task join happens and one branch modifies one variable and another branch modifies another variable, the last branch that merges the context for the join task will overwrite the variables for the other branch. With this change, only diff in the context is stored after each task transition and the join task will merge the diffs chronologically. This will also reduce the memory footprint used by the internal data structure because only diffs are stored. Fixes #112
> Fix overwritten context variables on task join

- orquesta/exceptions.py
- orquesta/expressions/functions/common.py
- orquesta/specs/base.py
- orquesta/tests/unit/conducting/test_workflow_conductor_context.py
- orquesta/tests/unit/expressions/functions/test_common.py
The workflow execution context contains internal variables prefixed with double underscores that contain state information. Spec inspection is refactored to prevent references of variables prefixed with double underscores when using the ctx function. The ctx function is refactored to not return any variables prefixed with double underscores.
> Restrict ctx function from returning internal vars

- orquesta/machines.py
- orquesta/tests/unit/conducting/test_workflow_conductor_pending_and_resume.py
A workflow goes into paused status when a task goes into pending status. If the task transition has error, the workflow does not go into failed status when the task is completed. This patch add an entry in the state machine for workflow to go from paused to failed status.
> Fix task transition error on completing task in pending status

- CHANGELOG.rst
- orquesta/conducting.py
- orquesta/tests/fixtures/workflows/native/error-log-fail-concurrent.yaml
- orquesta/tests/unit/base.py
- orquesta/tests/unit/conducting/native/test_workflow_error_handling.py
Allow tasks in the same transition with a "fail" command to be staged. These tasks will be returned when get_next_tasks is called even when the workflow execution has failed. Closes #113
> Allow tasks in the same transition with fail to run

- Makefile
Part of https://github.com/StackStorm/st2/issues/4681 
With https://github.com/StackStorm/st2-packages/pull/614 and https://github.com/StackStorm/st2packaging-dockerfiles/pull/70 we can upgrade previously pinned pip 9 to currently latest one.
Related PR in st2: https://github.com/StackStorm/st2/pull/4712
> Upgrade pip from 9.x to currently latest one

- CHANGELOG.rst
- orquesta/specs/native/v1/models.py
- orquesta/tests/unit/specs/native/test_workflow_spec_validate.py
Rephrased the error message for unreachable join task to be more descriptive and clearer to the user why the join task is unreachable. Fixes #162.
> Rephrased error message for unreachable join task

- CHANGELOG.rst
- orquesta/expressions/jinja.py
- orquesta/tests/unit/expressions/test_jinja_eval_raw_blocks.py
If there is a for loop in the Jinja block expression and the item is a complex data type, the current Jinja evaluator converted the item into string type. So if the item is a dictionary, and user tries to access some key value pair, the Jinja evaluator returns an error saying the item is undefined. The Jinja evaluator tries to evaluate individual expression first, even for expression within the for loop, before evaluating the block expression which resulted in the undefined error when the item of the for loop is referenced. To fix, the text is checked to see if there is a Jinja block expression. If there is a Jinja block expression, the entire text is rendered together. Otherwise, if there is no Jinja block expression, then standalone expressions will be rendered individually to preserve …
> Fix Jinja evaluator to evaluate block expression correctly

- CHANGELOG.rst
- orquesta/conducting.py
- orquesta/tests/fixtures/workflows/native/cycle-fork.yaml
- orquesta/tests/unit/conducting/native/test_workflow_cycle.py
If there is a branch that fork from a cycle in the workflow graph, during runtime and the workflow runs the cycle more than once, tasks under the forked branch will not execute a second time. The issue is caused by the networkx graph not recognizing the forked branch as part of the cycle. The conductor is changed to determine a task is executed more than once as part of the cycle when the last task entry is completed and the new task status is one of the starting execution statuses. Fixes #169
> Fix conducting of cycle with a fork

- CHANGELOG.rst
- orquesta/conducting.py
- orquesta/tests/unit/conducting/test_workflow_conductor_cancel.py
- orquesta/tests/unit/conducting/test_workflow_conductor_pause_and_resume.py
If a workflow is still pausing and pause is requested again, request_workflow_status will not be able to change the workflow status to paused. This is normal and exception should not be raised. This is a similar case for workflow cancelation.
>  Fix request_workflow_status to ignore certain status change errors

- CHANGELOG.rst
- orquesta/conducting.py
- orquesta/events.py
- orquesta/machines.py
- orquesta/tests/unit/base.py
- orquesta/tests/unit/conducting/test_workflow_conductor_with_items_cancel.py
- orquesta/tests/unit/conducting/test_workflow_conductor_with_items_pause_and_resume.py
- orquesta/tests/unit/states/native/test_workflow_with_items.py
- orquesta/tests/unit/states/native/test_workflow_with_items_cancel.py
- orquesta/tests/unit/states/native/test_workflow_with_items_pause_and_resume.py
Refactor conductor to not store individual item result for a with items task in the task state. If there are a lot of items and/or result size is huge per item, then this will be a performance impact on database write operations when recording the conductor state. A new TaskItemActionExecutionEvent is introduced to distinguish between a normal action execution event and one for an item. The accumulated result is only stored temporary in the conductor state and evaluated by the conductor when all the items have completed execution.
> Refactor conductor to not store each item result in task state

- CHANGELOG.rst
- orquesta/conducting.py
- orquesta/tests/unit/base.py
- orquesta/tests/unit/conducting/test_workflow_conductor.py
- orquesta/tests/unit/conducting/test_workflow_conductor_branching.py
- orquesta/tests/unit/conducting/test_workflow_conductor_cancel.py
- orquesta/tests/unit/conducting/test_workflow_conductor_context.py
- orquesta/tests/unit/conducting/test_workflow_conductor_data_flow.py
- orquesta/tests/unit/conducting/test_workflow_conductor_error_handling.py
- orquesta/tests/unit/conducting/test_workflow_conductor_performance.py
- orquesta/tests/unit/conducting/test_workflow_conductor_task_status.py
- orquesta/tests/unit/conducting/test_workflow_conductor_with_items.py
In certain use case, the service using orquesta gets the final task status only after updating the task state. If the rendering of workflow output on completion of the workflow execution calls a task related function to get task status and result such as the `task` function in StackStorm, the render would return an inaccurate task state. To address this issue, the rendering of workflow output is not done by default when updating the task state. The services consuming orquesta need to render workflow output separately and explicitly. The service should update task state, then check the workflow status before rendering the workflow output.
> Separate render workflow output from update task state

- CHANGELOG.rst
- orquesta/expressions/base.py
When inspecting custom YAQL/Jinja function to see if there is a context arg in orquesta.expressions.base.func_has_ctx_arg, use getargspec for py2 and getfullargspec for py3.
> Fix func_has_ctx_arg to use getfullargspec for py3

- CHANGELOG.rst
- orquesta/conducting.py
- orquesta/graphing.py
- orquesta/machines.py
- orquesta/specs/mistral/v2/tasks.py
- orquesta/specs/native/v1/models.py
- orquesta/tests/unit/base.py
- orquesta/tests/unit/conducting/test_workflow_conductor.py
- orquesta/tests/unit/conducting/test_workflow_conductor_branching.py
- orquesta/tests/unit/conducting/test_workflow_conductor_data_flow.py
- orquesta/tests/unit/expressions/functions/test_workflow.py
- orquesta/tests/unit/expressions/test_yaql_ctx_query.py
- orquesta/tests/unit/graphing/test_workflow_graph.py
- orquesta/tests/unit/specs/test_base_spec.py
- orquesta/tests/unit/specs/test_base_spec_serialize.py
- orquesta/tests/unit/utils/test_context.py
- orquesta/tests/unit/utils/test_dictionary.py
- orquesta/utils/context.py
- orquesta/utils/jsonify.py
- orquesta/utils/schema.py
- requirements.txt
Use ujson for copying dict(s) instead of copy.deepcopy for better performance. There are specific cases where we have to continue using copy.deepcopy, specifically in merging schema because it contains Spec class(es).
> Use ujson to deepcopy dict(s) for faster performance

- CHANGELOG.rst
- Makefile
- docs/source/languages/orquesta.rst
- docs/source/schemas/mistral.json
- docs/source/schemas/orquesta.json
- orquesta/conducting.py
- orquesta/constants.py
- orquesta/exceptions.py
- orquesta/graphing.py
- orquesta/machines.py
- orquesta/tests/fixtures/workflows/native/join-all-complex.yaml
- orquesta/tests/fixtures/workflows/native/join-count-complex.yaml
- orquesta/tests/fixtures/workflows/native/join-on-complete.yaml
- orquesta/tests/fixtures/workflows/native/join-on-fail.yaml
- orquesta/tests/unit/base.py
- orquesta/tests/unit/composition/native/test_workflow_join.py
- orquesta/tests/unit/conducting/native/test_workflow_join.py
- orquesta/tests/unit/graphing/test_workflow_graph.py
- orquesta/utils/jsonify.py
Refactor evaluation of inbound criteria for join task on inbound task completion and not on inbound task transition. This allows for different use cases such as multiple task transition from the same inbound task, inbound task transition on completion or inbound task transition on failure. Include additional check in the state machine to detect case where there is an unreachable join task where inbound criteria is partially satisfied but all inbound tasks have already completed and it will never be satisfied.
Fixes https://github.com/StackStorm/orquesta/issues/123
Fixes https://github.com/StackStorm/orquesta/issues/190
> Refactor evaluation of inbound criteria for join task

- CHANGELOG.rst
- orquesta/specs/native/v1/models.py
- orquesta/tests/unit/base.py
- orquesta/tests/unit/conducting/test_workflow_conductor_with_items.py
Users can accidentally indent the action under the with statement. Fix the JSON schema for the with items task to not allow additional properties. Inspection of the workflow definition will throw a syntax exception. Fixes https://github.com/StackStorm/orquesta/issues/184.
> Fix schema of with items task to not allow additional properties

- orquesta/expressions/jinja.py
- orquesta/tests/unit/expressions/test_facade_jinja_ctx_by_dot_notation.py
- orquesta/tests/unit/expressions/test_facade_jinja_ctx_by_function_arg.py
This PR cleans up some of the regexes that are used to recognize context references and extract variable names. I also added a few more strings to the tests.
I can do some further cleanup, but it would make the regexes a lot more complicated to understand (but probably slightly faster to execute).
> Simplify Jinja expression context regexes

- CHANGELOG.rst
- orquesta/expressions/base.py
- orquesta/expressions/jinja.py
- orquesta/expressions/yql.py
- orquesta/tests/unit/expressions/test_facade_jinja_ctx_by_dot_notation.py
- orquesta/tests/unit/expressions/test_facade_jinja_ctx_by_function_arg.py
- orquesta/tests/unit/expressions/test_facade_yaql_ctx_by_dot_notation.py
- orquesta/tests/unit/expressions/test_facade_yaql_ctx_by_function_arg.py
- orquesta/tests/unit/expressions/test_jinja_ctx_by_dot_notation.py
- orquesta/tests/unit/expressions/test_jinja_ctx_by_function_arg.py
- orquesta/tests/unit/expressions/test_yaql_ctx_by_dot_notation.py
- orquesta/tests/unit/expressions/test_yaql_ctx_by_function_arg.py
The ctx() method returns a dict and there are use cases where users call supported methods on the dict such as keys(), values(), and get().  The vars extraction would return false positives on these function calls. The regular expressions to extract variables from expressions is refactored to ignore these dict related function calls directly on ctx(). Fixes https://github.com/StackStorm/st2/issues/4866.
> Fix the yaql/jinja vars extraction to ignore methods of base ctx() dict

- CHANGELOG.rst
- orquesta/expressions/functions/workflow.py
- orquesta/expressions/yql.py
- orquesta/tests/unit/conducting/native/test_task_rendering_for_with_items.py
- orquesta/tests/unit/conducting/test_workflow_conductor_data_flow.py
- orquesta/tests/unit/expressions/test_facade_yaql_evaluate.py
This fixes a problem not to be able to parse data which is typed dict(etc) in array in some YAQL operators by converting input data-structure from unhashable value to hashable one. (c.f. #176)
Orquesta couldn't handle dict in array typed value in some yqal operators (e.g. `distinct`) as below.
```
username@host:~$ cd st2
username@host:~/st2$ source virtualenv/bin/activate; python
>>> from orquesta.expressions import base as expr_base
>>>
>>> data = {'val': ['foo', 'bar', 'foo']}
>>> expr_base.evaluate("<% ctx(val) %>", data)
['foo', 'bar', 'foo']
>>> expr_base.evaluate("<% ctx(val).distinct() %>", data)
['foo', 'bar']
>>>
>>> data = {'val': [{'a': 1}, {'b': 2}, {'a': 1}]}
>>> expr_base.evaluate("<% ctx(val) %>", data)
[{'a': 1}, {'b': 2}, {'a': 1}]
>>> expr_base.evaluate("<% …
```
> Fixed a problem not to be able to parse input value which is type of dict in array in some YAQL operators.

- CHANGELOG.rst
- orquesta/conducting.py
- orquesta/tests/unit/conducting/test_task_retry.py
Fix issue when a task that has a transition on failure will also traverse the transition on retry. The issue is caused by the recursion on update_task_state. There should be a return in the recursive call.
> Fix remediated task with retry

- Makefile
On more modern versions of `virtualenv`, the long-deprecated `--no-site-packages` flag has finally been removed, so `make reqs` errors out:
```bash
$ make reqs
test -d .venv || virtualenv -p /Library/Frameworks/Python.framework/Versions/3.8/bin/python3 --no-site-packages .venv
usage: virtualenv [--version] [--with-traceback] [-v | -q] [--discovery {builtin}] [-p py] [--creator {builtin,cpython3-posix,venv}] [--seeder {app-data,pip}] [--no-seed] [--activators comma_separated_list] [--clear]
[--system-site-packages] [--symlinks | --copies] [--download | --no-download] [--extra-search-dir d [d ...]] [--pip version] [--setuptools version] [--wheel version] [--no-pip] [--no-setuptools] [--no-wheel]
[--clear-app-data] [--symlink-app-data] [--prompt prompt] [-h]
dest
virtualenv: error: …
```
> Remove deprecated (and now removed) --no-site-packages flag when creating a venv

- orquesta/tests/unit/conducting/test_workflow_conductor_rerun.py
Minor changes to the workflow definition in the tests for task rerun. Ensure that the workflow will continue to run subsequent tasks following the task that is rerun.
> Minor changes to tests for task rerun

- Makefile
- requirements-test.txt
Add twine to requirements file. Add make command to run twine to publish package to pypi.
> Add make command to publish package to pypi

- CHANGELOG.rst
- orquesta/expressions/base.py
- orquesta/expressions/functions/base.py
Acquire a lock before initializing global vars to ensure thread safety. Otherwise, it is possible race can occur between multiple threads when initializing the vars.
> Lock global vars during initialization for thread safety

- docs/source/languages/orquesta.rst
Update documents to explain fail fast design.
Designed to explain the confusion on when workflows stop, raised in https://github.com/StackStorm/st2/issues/5031.
> Expand docs to explain fail-fast design

- CHANGELOG.rst
- orquesta/utils/parameters.py
The "(?i)" flag from regex parts used to build the expression for checking inline parameters results in deprecation warning from python3 regex module. The regex change here avoids the deprecation warning that flags are not at the start of the expression.
> Remove flags from regex parts for inline parameters

- CHANGELOG.rst
- orquesta/specs/base.py
- orquesta/specs/native/v1/models.py
- orquesta/tests/hacking/import_aliases_rule.py
- orquesta/tests/unit/specs/native/test_workflow_spec_validate.py
- orquesta/utils/specs.py
- orquesta/utils/yml.py
Add custom constructor in YAML SafeLoader to throw exception if there are duplicate keys in the YAML for the workflow definition. Fixes https://github.com/StackStorm/orquesta/issues/147.
> Add constructor in YAML SafeLoader to check duplicate keys

- Makefile
st2 core uses pip 20.0.2. Do the same here.
> Use the same version of pip as st2 core

- .github/workflows/tox.yml
- tox.ini
This PR adds Python3.8 support to orquesta testing as part of the Ubuntu 20.04 support work https://github.com/StackStorm/discussions/issues/68
> Add python3.8 support to tests using tox-gh-actions

- .gitignore
- orquesta/graphing.py
- orquesta/tests/unit/conducting/test_workflow_conductor.py
- requirements.txt
Orquesta won't run on python 3.9+ because it currently has a dependency on  `networkx` version 1.11. It doesn't look like the 1.x version of `networkx` has received any updates in quite a while. In Python 3.9, the `gcd` function used by `networkx` was moved from `functions` to `math` package in the standard lib [as described here](https://stackoverflow.com/questions/66174862/import-error-cant-import-name-gcd-from-fractions). This PR updates orquesta to use the latest version of `networkx` which is currently 2.5.1.
The code has been modified where necessary and all tests are passing on my machine with Python 3.9.5. Let me know if there is anything else necessary. Thanks.
> upgrade to latest networkx to allow running on py 3.9

- CHANGELOG.rst
- orquesta/expressions/jinja.py
- requirements-docs.txt
- requirements.txt
Use Jinja sandboxed environment, so that any templates that attempt to access insecure code will be rejected.
> Use Jinja sandboxed environment

- CHANGELOG.rst
- orquesta/composers/native.py
- orquesta/specs/native/v1/models.py
- orquesta/tests/unit/conducting/test_workflow_conductor_performance.py
Workflows which has many task or if multiple tasks are going to common task in the flow, execution of such workflows take lot of time in inspect and serialize of workflow definition.
In `st2common/services/workflows.py`
https://github.com/StackStorm/st2/blob/master/st2common/st2common/services/workflows.py#L230
```
inspect(wf_spec, st2_ctx, raise_exception=True)
```
https://github.com/StackStorm/st2/blob/master/st2common/st2common/services/workflows.py#L255
```
data = conductor.serialize()
```
Some of our workflows are very complex with many task and when-do conditions.Even in some workflows it was taking hours in conductor serialization.
**Proposed Solution:**
In inspect and conductor serialization, while adding the task and its splits to the queue also keep a separate track of task and …
> Optimise inspect and workflow graph generation logic

- requirements.txt
Update requirements to match st2 https://github.com/StackStorm/st2/pull/5376
> Pin networkx to versions lower than 2.6 which doesn't support Python 3.6

- orquesta/commands/rehearsal.py
When debugging an entire folder of workflow tests using the `-d` flag it is not clear which test fixture is causing spec errors.  This PR adds a log.info output line so that it is clear to the user which fixture caused a spec error.
```
2021-12-17 15:25:59,693 - INFO - The test spec "././workflow_tests//process_single.yaml" is successfully loaded.
2021-12-17 15:25:59,693 - INFO - Start test for workflow "./actions/workflows/process_single.yaml".
2021-12-17 15:25:59,725 - DEBUG - Task "initial_ticket__r0" is set to "running".
2021-12-17 15:25:59,726 - DEBUG - Applying action execution with "succeeded" status to task "initial_ticket__r0".
2021-12-17 15:25:59,735 - DEBUG - Task "initial_ticket__r0" is set to "succeeded".
2021-12-17 15:25:59,746 - DEBUG - Task "add_indicators_mitigate__r0" is …
```
> add 'Initiating test spec' to process to make debugging clear

- CHANGELOG.rst
- orquesta/__init__.py
Preparing a release of orquesta for st2. Update orquesta version from 1.5.0 to 1.6.0.
> Prepare for orquesta v1.6.0 release

- orquesta/conducting.py
- orquesta/tests/unit/conducting/test_workflow_conductor_with_items.py
This may not be the most optimal fix, there might be a better way to address the issue of 0 through schema validation.
> Set concurrency to 1 if 0 supplied. Fix #259

- .github/workflows/tox.yml
- .pylintrc
- CHANGELOG.rst
- Makefile
- requirements-ci.txt
- requirements-docs.txt
- requirements-test.txt
- requirements.txt
- setup.py
- tox.ini
This set of patches is required as part of the updates needed to support py3.8, py3.9 and py3.10.  This PR is a blocking dependency for https://github.com/StackStorm/st2/pull/6157
> Use hacking fork as dependency and align modules with stackstorm core.

- orquesta/rehearsing.py
During usage you would before see something to the effect of:
```bash
2024-04-16 00:00:00,000 - ERROR - {'context': [{'type': 'jinja', 'expression[2500 chars]t'}]} != {}
Diff is 4500 characters long. Set self.maxDiff to None to see it.
```
This change will make it so that that error no longer shows up.
> Update rehearsing.py to disable limit of output errors during workflow testing.
